// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.google.research.bleth.simulator;

public interface PersonsListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PersonsList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Person persons = 1;</code>
   */
  java.util.List<com.google.research.bleth.simulator.Person> 
      getPersonsList();
  /**
   * <code>repeated .Person persons = 1;</code>
   */
  com.google.research.bleth.simulator.Person getPersons(int index);
  /**
   * <code>repeated .Person persons = 1;</code>
   */
  int getPersonsCount();
  /**
   * <code>repeated .Person persons = 1;</code>
   */
  java.util.List<? extends com.google.research.bleth.simulator.PersonOrBuilder> 
      getPersonsOrBuilderList();
  /**
   * <code>repeated .Person persons = 1;</code>
   */
  com.google.research.bleth.simulator.PersonOrBuilder getPersonsOrBuilder(
      int index);
}
