// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.google.research.bleth.simulator;

/**
 * Protobuf type {@code PersonsList}
 */
public  final class PersonsList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PersonsList)
    PersonsListOrBuilder {
  // Use PersonsList.newBuilder() to construct.
  private PersonsList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PersonsList() {
    persons_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private PersonsList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              persons_ = new java.util.ArrayList<com.google.research.bleth.simulator.Person>();
              mutable_bitField0_ |= 0x00000001;
            }
            persons_.add(
                input.readMessage(com.google.research.bleth.simulator.Person.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        persons_ = java.util.Collections.unmodifiableList(persons_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.research.bleth.simulator.PersonOuterClass.internal_static_PersonsList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.research.bleth.simulator.PersonOuterClass.internal_static_PersonsList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.research.bleth.simulator.PersonsList.class, com.google.research.bleth.simulator.PersonsList.Builder.class);
  }

  public static final int PERSONS_FIELD_NUMBER = 1;
  private java.util.List<com.google.research.bleth.simulator.Person> persons_;
  /**
   * <code>repeated .Person persons = 1;</code>
   */
  public java.util.List<com.google.research.bleth.simulator.Person> getPersonsList() {
    return persons_;
  }
  /**
   * <code>repeated .Person persons = 1;</code>
   */
  public java.util.List<? extends com.google.research.bleth.simulator.PersonOrBuilder> 
      getPersonsOrBuilderList() {
    return persons_;
  }
  /**
   * <code>repeated .Person persons = 1;</code>
   */
  public int getPersonsCount() {
    return persons_.size();
  }
  /**
   * <code>repeated .Person persons = 1;</code>
   */
  public com.google.research.bleth.simulator.Person getPersons(int index) {
    return persons_.get(index);
  }
  /**
   * <code>repeated .Person persons = 1;</code>
   */
  public com.google.research.bleth.simulator.PersonOrBuilder getPersonsOrBuilder(
      int index) {
    return persons_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < persons_.size(); i++) {
      output.writeMessage(1, persons_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < persons_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, persons_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.research.bleth.simulator.PersonsList)) {
      return super.equals(obj);
    }
    com.google.research.bleth.simulator.PersonsList other = (com.google.research.bleth.simulator.PersonsList) obj;

    boolean result = true;
    result = result && getPersonsList()
        .equals(other.getPersonsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getPersonsCount() > 0) {
      hash = (37 * hash) + PERSONS_FIELD_NUMBER;
      hash = (53 * hash) + getPersonsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.research.bleth.simulator.PersonsList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.research.bleth.simulator.PersonsList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.research.bleth.simulator.PersonsList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.research.bleth.simulator.PersonsList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.research.bleth.simulator.PersonsList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.research.bleth.simulator.PersonsList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.research.bleth.simulator.PersonsList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.research.bleth.simulator.PersonsList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.research.bleth.simulator.PersonsList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.research.bleth.simulator.PersonsList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.research.bleth.simulator.PersonsList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PersonsList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PersonsList)
      com.google.research.bleth.simulator.PersonsListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.research.bleth.simulator.PersonOuterClass.internal_static_PersonsList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.research.bleth.simulator.PersonOuterClass.internal_static_PersonsList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.research.bleth.simulator.PersonsList.class, com.google.research.bleth.simulator.PersonsList.Builder.class);
    }

    // Construct using com.google.research.bleth.simulator.PersonsList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPersonsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (personsBuilder_ == null) {
        persons_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        personsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.research.bleth.simulator.PersonOuterClass.internal_static_PersonsList_descriptor;
    }

    public com.google.research.bleth.simulator.PersonsList getDefaultInstanceForType() {
      return com.google.research.bleth.simulator.PersonsList.getDefaultInstance();
    }

    public com.google.research.bleth.simulator.PersonsList build() {
      com.google.research.bleth.simulator.PersonsList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.research.bleth.simulator.PersonsList buildPartial() {
      com.google.research.bleth.simulator.PersonsList result = new com.google.research.bleth.simulator.PersonsList(this);
      int from_bitField0_ = bitField0_;
      if (personsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          persons_ = java.util.Collections.unmodifiableList(persons_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.persons_ = persons_;
      } else {
        result.persons_ = personsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.research.bleth.simulator.PersonsList) {
        return mergeFrom((com.google.research.bleth.simulator.PersonsList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.research.bleth.simulator.PersonsList other) {
      if (other == com.google.research.bleth.simulator.PersonsList.getDefaultInstance()) return this;
      if (personsBuilder_ == null) {
        if (!other.persons_.isEmpty()) {
          if (persons_.isEmpty()) {
            persons_ = other.persons_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePersonsIsMutable();
            persons_.addAll(other.persons_);
          }
          onChanged();
        }
      } else {
        if (!other.persons_.isEmpty()) {
          if (personsBuilder_.isEmpty()) {
            personsBuilder_.dispose();
            personsBuilder_ = null;
            persons_ = other.persons_;
            bitField0_ = (bitField0_ & ~0x00000001);
            personsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPersonsFieldBuilder() : null;
          } else {
            personsBuilder_.addAllMessages(other.persons_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.research.bleth.simulator.PersonsList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.research.bleth.simulator.PersonsList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.research.bleth.simulator.Person> persons_ =
      java.util.Collections.emptyList();
    private void ensurePersonsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        persons_ = new java.util.ArrayList<com.google.research.bleth.simulator.Person>(persons_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.research.bleth.simulator.Person, com.google.research.bleth.simulator.Person.Builder, com.google.research.bleth.simulator.PersonOrBuilder> personsBuilder_;

    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public java.util.List<com.google.research.bleth.simulator.Person> getPersonsList() {
      if (personsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(persons_);
      } else {
        return personsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public int getPersonsCount() {
      if (personsBuilder_ == null) {
        return persons_.size();
      } else {
        return personsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public com.google.research.bleth.simulator.Person getPersons(int index) {
      if (personsBuilder_ == null) {
        return persons_.get(index);
      } else {
        return personsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public Builder setPersons(
        int index, com.google.research.bleth.simulator.Person value) {
      if (personsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonsIsMutable();
        persons_.set(index, value);
        onChanged();
      } else {
        personsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public Builder setPersons(
        int index, com.google.research.bleth.simulator.Person.Builder builderForValue) {
      if (personsBuilder_ == null) {
        ensurePersonsIsMutable();
        persons_.set(index, builderForValue.build());
        onChanged();
      } else {
        personsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public Builder addPersons(com.google.research.bleth.simulator.Person value) {
      if (personsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonsIsMutable();
        persons_.add(value);
        onChanged();
      } else {
        personsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public Builder addPersons(
        int index, com.google.research.bleth.simulator.Person value) {
      if (personsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonsIsMutable();
        persons_.add(index, value);
        onChanged();
      } else {
        personsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public Builder addPersons(
        com.google.research.bleth.simulator.Person.Builder builderForValue) {
      if (personsBuilder_ == null) {
        ensurePersonsIsMutable();
        persons_.add(builderForValue.build());
        onChanged();
      } else {
        personsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public Builder addPersons(
        int index, com.google.research.bleth.simulator.Person.Builder builderForValue) {
      if (personsBuilder_ == null) {
        ensurePersonsIsMutable();
        persons_.add(index, builderForValue.build());
        onChanged();
      } else {
        personsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public Builder addAllPersons(
        java.lang.Iterable<? extends com.google.research.bleth.simulator.Person> values) {
      if (personsBuilder_ == null) {
        ensurePersonsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, persons_);
        onChanged();
      } else {
        personsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public Builder clearPersons() {
      if (personsBuilder_ == null) {
        persons_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        personsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public Builder removePersons(int index) {
      if (personsBuilder_ == null) {
        ensurePersonsIsMutable();
        persons_.remove(index);
        onChanged();
      } else {
        personsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public com.google.research.bleth.simulator.Person.Builder getPersonsBuilder(
        int index) {
      return getPersonsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public com.google.research.bleth.simulator.PersonOrBuilder getPersonsOrBuilder(
        int index) {
      if (personsBuilder_ == null) {
        return persons_.get(index);  } else {
        return personsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public java.util.List<? extends com.google.research.bleth.simulator.PersonOrBuilder> 
         getPersonsOrBuilderList() {
      if (personsBuilder_ != null) {
        return personsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(persons_);
      }
    }
    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public com.google.research.bleth.simulator.Person.Builder addPersonsBuilder() {
      return getPersonsFieldBuilder().addBuilder(
          com.google.research.bleth.simulator.Person.getDefaultInstance());
    }
    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public com.google.research.bleth.simulator.Person.Builder addPersonsBuilder(
        int index) {
      return getPersonsFieldBuilder().addBuilder(
          index, com.google.research.bleth.simulator.Person.getDefaultInstance());
    }
    /**
     * <code>repeated .Person persons = 1;</code>
     */
    public java.util.List<com.google.research.bleth.simulator.Person.Builder> 
         getPersonsBuilderList() {
      return getPersonsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.research.bleth.simulator.Person, com.google.research.bleth.simulator.Person.Builder, com.google.research.bleth.simulator.PersonOrBuilder> 
        getPersonsFieldBuilder() {
      if (personsBuilder_ == null) {
        personsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.research.bleth.simulator.Person, com.google.research.bleth.simulator.Person.Builder, com.google.research.bleth.simulator.PersonOrBuilder>(
                persons_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        persons_ = null;
      }
      return personsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:PersonsList)
  }

  // @@protoc_insertion_point(class_scope:PersonsList)
  private static final com.google.research.bleth.simulator.PersonsList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.research.bleth.simulator.PersonsList();
  }

  public static com.google.research.bleth.simulator.PersonsList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PersonsList>
      PARSER = new com.google.protobuf.AbstractParser<PersonsList>() {
    public PersonsList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersonsList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PersonsList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PersonsList> getParserForType() {
    return PARSER;
  }

  public com.google.research.bleth.simulator.PersonsList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

